"""major changes

Revision ID: 7e5b15e7b7f1
Revises: 777feddd5d2c
Create Date: 2020-05-09 21:52:26.740507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5b15e7b7f1'
down_revision = '777feddd5d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('latitude', sa.Numeric(), nullable=True))
    op.add_column('answers', sa.Column('longitude', sa.Numeric(), nullable=True))
    op.add_column('answers', sa.Column('province', sa.Text(), nullable=True))
    op.add_column('answers', sa.Column('q1', sa.Enum('Yes', 'No', name='Answer'), nullable=True))
    op.add_column('answers', sa.Column('q2', sa.Enum('Yes', 'No', name='Answer'), nullable=True))
    op.add_column('answers', sa.Column('q3', sa.Enum('Yes', 'No', name='Answer'), nullable=True))
    op.add_column('answers', sa.Column('q4', sa.Enum('Yes', 'No', name='Answer'), nullable=True))
    op.add_column('answers', sa.Column('q5', sa.Enum('Yes', 'No', name='Answer'), nullable=True))
    op.add_column('answers', sa.Column('q6', sa.Enum('Yes', 'No', name='Answer'), nullable=True))
    op.add_column('answers', sa.Column('q7', sa.Enum('Yes', 'No', name='Answer'), nullable=True))
    op.add_column('answers', sa.Column('q8', sa.Enum('Yes', 'No', name='Answer'), nullable=True))
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_column('answers', 'question')
    op.drop_column('answers', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('text', sa.TEXT(), nullable=True))
    op.add_column('answers', sa.Column('question', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'answers', 'questions', ['question'], ['id'])
    op.drop_column('answers', 'q8')
    op.drop_column('answers', 'q7')
    op.drop_column('answers', 'q6')
    op.drop_column('answers', 'q5')
    op.drop_column('answers', 'q4')
    op.drop_column('answers', 'q3')
    op.drop_column('answers', 'q2')
    op.drop_column('answers', 'q1')
    op.drop_column('answers', 'province')
    op.drop_column('answers', 'longitude')
    op.drop_column('answers', 'latitude')
    # ### end Alembic commands ###
